# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zhengzhihust's Blog
email: 1424798497@qq.com
description: > # 花名元朗，蘑菇街Java高级开发工程师，毕业于华中科技大学
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  https://github.com/zhengzhihust

# Build settings
markdown: kramdown
